# This is a basic workflow to help you get started with Actions

name: Deploy NuGet

# Controls when the workflow will run
on:
  # Triggers the workflow on push only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Update NuGet package

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # SDK Version to use
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      # Runs a set of commands using the runners shell
      - name: Add NuGet Source
        run: dotnet nuget add source --username briandoesdev --password ${{ secrets.NUGET_API_KEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/briandoesdev/index.json"
      - name: Run and build package
        run: dotnet pack -c Release -o out
          
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./out/*.nupkg --source github --skip-duplicate --no-symbols true
